### PR TITLE
Deprecate using the macro from Base

### PR DESCRIPTION
**Pull request by ararslan**
As promised in https://github.com/JuliaStats/TimeSeries.jl/pull/281#discussion_r77683125

### CODE REVIEW

**Comment by milktrader** [comment]
Sweet refactor, takes out quite a few lines of code. 

These tests should pass after I merge #281

**Comment by ararslan** [comment]
> These tests should pass after I merge #281

I'm glad you know that, because I was stumped as to why they were failing. 😜 Once that's merged I'll likely need to rebase, so that'll trigger a rebuild on Travis and we can see if things do indeed work.

**Comment by milktrader** [comment]
I checked out this PR and rebased it but ran into an error.

````julia
while loading /Users/Administrator/.julia/v0.5/TimeSeries/test/deprecated.jl, in expression starting on line 5
EEEE
  Error :: (line:272)
    Expression: collapse(cl,last).values[1] --> 99.5
    function collapse does not accept keyword arguments
     in kwfunc(::Any) at ./boot.jl:236
     in collapse(::TimeSeries.TimeArray{Float64,1,Date,Array{Float64,1}}, ::Function, ::Function) at ./deprecated.jl:52
     in collapse(::TimeSeries.TimeArray{Float64,1,Date,Array{Float64,1}}, ::Function) at ./deprecated.jl:50
     in (::##50#106{##49#105})() at /Users/Administrator/.julia/v0.5/FactCheck/src/FactCheck.jl:272
     in do_fact(::##50#106{##49#105}, ::Expr, ::Symbol, ::FactCheck.ResultMetadata) at /Users/Administrator/.julia/v0.5/FactCheck/src/FactCheck.jl:334
     in macro expansion at /Users/Administrator/.julia/v0.5/FactCheck/src/FactCheck.jl:272 [inlined]
     in (::##48#104)() at /Users/Administrator/.julia/v0.5/TimeSeries/test/deprecated.jl:43
     in context(::##48#104, ::String) at /Users/Administrator/.julia/v0.5/FactCheck/src/FactCheck.jl:475
     in (::##1#57)() at /Users/Administrator/.julia/v0.5/TimeSeries/test/deprecated.jl:42
     in facts(::##1#57, ::String) at /Users/Administrator/.julia/v0.5/FactCheck/src/FactCheck.jl:449
     in include_from_node1(::String) at ./loading.jl:426
     in include_from_node1(::String) at /Users/Administrator/.pantry/julia-0.5rc3/julia/usr/lib/julia/sys.dylib:?
     in @test(::Any, ::Symbol, ::Vararg{Symbol,N}) at /Users/Administrator/.juliarc.jl:5
     in eval(::Module, ::Any) at ./boot.jl:234
     in eval(::Module, ::Any) at /Users/Administrator/.pantry/julia-0.5rc3/julia/usr/lib/julia/sys.dylib:?
     in eval_user_input(::Any, ::Base.REPL.REPLBackend) at ./REPL.jl:64
     in macro expansion at ./REPL.jl:95 [inlined]
     in (::Base.REPL.##3#4{Base.REPL.REPLBackend})() at ./event.jl:68
  Error :: (line:272)
    Expression: collapse(cl,last).timestamp[1] --> Date(2000,1,7)
    function collapse does not accept keyword arguments
     in kwfunc(::Any) at ./boot.jl:236
     in collapse(::TimeSeries.TimeArray{Float64,1,Date,Array{Float64,1}}, ::Function, ::Function) at ./deprecated.jl:52
     in collapse(::TimeSeries.TimeArray{Float64,1,Date,Array{Float64,1}}, ::Function) at ./deprecated.jl:50
     in (::##52#108{##51#107})() at /Users/Administrator/.julia/v0.5/FactCheck/src/FactCheck.jl:272
     in do_fact(::##52#108{##51#107}, ::Expr, ::Symbol, ::FactCheck.ResultMetadata) at /Users/Administrator/.julia/v0.5/FactCheck/src/FactCheck.jl:334
     in macro expansion at /Users/Administrator/.julia/v0.5/FactCheck/src/FactCheck.jl:272 [inlined]
     in (::##48#104)() at /Users/Administrator/.julia/v0.5/TimeSeries/test/deprecated.jl:44
     in context(::##48#104, ::String) at /Users/Administrator/.julia/v0.5/FactCheck/src/FactCheck.jl:475
     in (::##1#57)() at /Users/Administrator/.julia/v0.5/TimeSeries/test/deprecated.jl:42
     in facts(::##1#57, ::String) at /Users/Administrator/.julia/v0.5/FactCheck/src/FactCheck.jl:449
     in include_from_node1(::String) at ./loading.jl:426
     in include_from_node1(::String) at /Users/Administrator/.pantry/julia-0.5rc3/julia/usr/lib/julia/sys.dylib:?
     in @test(::Any, ::Symbol, ::Vararg{Symbol,N}) at /Users/Administrator/.juliarc.jl:5
     in eval(::Module, ::Any) at ./boot.jl:234
     in eval(::Module, ::Any) at /Users/Administrator/.pantry/julia-0.5rc3/julia/usr/lib/julia/sys.dylib:?
     in eval_user_input(::Any, ::Base.REPL.REPLBackend) at ./REPL.jl:64
     in macro expansion at ./REPL.jl:95 [inlined]
     in (::Base.REPL.##3#4{Base.REPL.REPLBackend})() at ./event.jl:68
  Error :: (line:272)
    Expression: collapse(cl,last,period=month).values[1] --> 103.75
    function collapse does not accept keyword arguments
     in kwfunc(::Any) at ./boot.jl:236
     in (::##54#110{##53#109})() at /Users/Administrator/.julia/v0.5/FactCheck/src/FactCheck.jl:272
     in do_fact(::##54#110{##53#109}, ::Expr, ::Symbol, ::FactCheck.ResultMetadata) at /Users/Administrator/.julia/v0.5/FactCheck/src/FactCheck.jl:334
     in macro expansion at /Users/Administrator/.julia/v0.5/FactCheck/src/FactCheck.jl:272 [inlined]
     in (::##48#104)() at /Users/Administrator/.julia/v0.5/TimeSeries/test/deprecated.jl:45
     in context(::##48#104, ::String) at /Users/Administrator/.julia/v0.5/FactCheck/src/FactCheck.jl:475
     in (::##1#57)() at /Users/Administrator/.julia/v0.5/TimeSeries/test/deprecated.jl:42
     in facts(::##1#57, ::String) at /Users/Administrator/.julia/v0.5/FactCheck/src/FactCheck.jl:449
     in include_from_node1(::String) at ./loading.jl:426
     in include_from_node1(::String) at /Users/Administrator/.pantry/julia-0.5rc3/julia/usr/lib/julia/sys.dylib:?
     in @test(::Any, ::Symbol, ::Vararg{Symbol,N}) at /Users/Administrator/.juliarc.jl:5
     in eval(::Module, ::Any) at ./boot.jl:234
     in eval(::Module, ::Any) at /Users/Administrator/.pantry/julia-0.5rc3/julia/usr/lib/julia/sys.dylib:?
     in eval_user_input(::Any, ::Base.REPL.REPLBackend) at ./REPL.jl:64
     in macro expansion at ./REPL.jl:95 [inlined]
     in (::Base.REPL.##3#4{Base.REPL.REPLBackend})() at ./event.jl:68
  Error :: (line:272)
    Expression: collapse(cl,last,period=month).timestamp[1] --> Date(2000,1,31)
    function collapse does not accept keyword arguments
     in kwfunc(::Any) at ./boot.jl:236
     in (::##56#112{##55#111})() at /Users/Administrator/.julia/v0.5/FactCheck/src/FactCheck.jl:272
     in do_fact(::##56#112{##55#111}, ::Expr, ::Symbol, ::FactCheck.ResultMetadata) at /Users/Administrator/.julia/v0.5/FactCheck/src/FactCheck.jl:334
     in macro expansion at /Users/Administrator/.julia/v0.5/FactCheck/src/FactCheck.jl:272 [inlined]
     in (::##48#104)() at /Users/Administrator/.julia/v0.5/TimeSeries/test/deprecated.jl:46
     in context(::##48#104, ::String) at /Users/Administrator/.julia/v0.5/FactCheck/src/FactCheck.jl:475
     in (::##1#57)() at /Users/Administrator/.julia/v0.5/TimeSeries/test/deprecated.jl:42
     in facts(::##1#57, ::String) at /Users/Administrator/.julia/v0.5/FactCheck/src/FactCheck.jl:449
     in include_from_node1(::String) at ./loading.jl:426
     in include_from_node1(::String) at /Users/Administrator/.pantry/julia-0.5rc3/julia/usr/lib/julia/sys.dylib:?
     in @test(::Any, ::Symbol, ::Vararg{Symbol,N}) at /Users/Administrator/.juliarc.jl:5
     in eval(::Module, ::Any) at ./boot.jl:234
     in eval(::Module, ::Any) at /Users/Administrator/.pantry/julia-0.5rc3/julia/usr/lib/julia/sys.dylib:?
     in eval_user_input(::Any, ::Base.REPL.REPLBackend) at ./REPL.jl:64
     in macro expansion at ./REPL.jl:95 [inlined]
     in (::Base.REPL.##3#4{Base.REPL.REPLBackend})() at ./event.jl:68
````

**Comment by ararslan** [comment]
I fixed that locally but was waiting to push the changes until after a rebase and conflict resolution.

**Comment by ararslan** [comment]
Cool, error fixed along with the conflicts upon rebase. Seems like the coverage drop may just be within noise, but regardless it should be unrelated.

**Pull request merged**
