### PR TITLE
Switched to DenseArray and implemented unary and binary logic

### PR DESCRIPTION
**Pull request by GordStephen**
Points 1-3 in https://github.com/JuliaStats/TimeSeries.jl/issues/196:

- Replace Arrays with DenseArrays
- Add unary logic and math operators
- Add binary logic operators
- Add tests for new operators
- Update docs with logic operators

### CODE REVIEW

**Comment by milktrader** [comment]
You need DenseArrays for binary logic operators I presume?

**Comment by GordStephen** [comment]
Yeah, `Base

**Comment by GordStephen** [comment]
Yeah, the `Base` logic operations on arrays return BitArrays, so directly using those results in a TimeArray requires DenseArray support.

**Comment by milktrader** [comment]
Why not use `Union{Array, BitArray}`?

**Comment by milktrader** [comment]
Also, where did you find the type hierarchy? From experimentation?

**Comment by GordStephen** [comment]
Yeah, for this, `Union{Array, BitArray}` would work just as well I think.

```julia
julia> super(Array)
DenseArray{T,N}

julia> super(BitArray)
DenseArray{Bool,N}

help?> DenseArray
DataType   : DenseArray{T,N}
  supertype: AbstractArray{T,N}
  subtypes : {Array{T,N},BitArray{N},SharedArray{T,N}}
```

**Comment by milktrader** [comment]
Ok, good old REPL exploration. Why not go for the gold and use `AbstractArray`?

**Comment by milktrader** [comment]
Probably goes to the issue of explication by elimination (see Jeff's thesis) in which case the more information you can provide the compiler, the better it is at optimizing. Before jumping over to `DenseArrays`, for example, it would be nice to get some benchmarks.

Here, btw, is `AbstractArray` subtypes:

````julia
help?> AbstractArray
search: AbstractArray AbstractSparseArray AbstractSparseMatrix

DataType   : AbstractArray{T,N}
  supertype: Any
  subtypes : Any[Base.LinAlg.AbstractTriangular{T,S<:AbstractArray{T,2}},Base.LinAlg.Bidiagonal{T},Base.LinAlg.Diagonal{T},Base.LinAlg.Hermitian{T,S<:AbstractArray{T,2}},Base.LinAlg.HessenbergQ{T,S<:AbstractArray{T,2}},Base.LinAlg.QRCompactWYQ{S,M<:AbstractArray{T,2}},Base.LinAlg.QRPackedQ{T,S<:AbstractArray{T,2}},Base.LinAlg.QRPackedWYQ{S,M<:AbstractArray{T,2}},Base.LinAlg.SVDOperator{T,S},Base.LinAlg.SymTridiagonal{T},Base.LinAlg.SymmetricRFP{T<:Union{Complex{Float64},Complex{Float32},Float64,Float32}},Base.LinAlg.Symmetric{T,S<:AbstractArray{T,2}},Base.LinAlg.TriangularRFP{T<:Union{Complex{Float64},Complex{Float32},Float64,Float32}},Base.LinAlg.Tridiagonal{T},Base.SparseMatrix.AbstractSparseArray{Tv,Ti,N},Base.SparseMatrix.CHOLMOD.FactorComponent{Tv,Ti,S},Core.Inference.Range{T},DenseArray{T,N},Range{T},SubArray{T,N,P<:AbstractArray{T,N},I<:Tuple{Vararg{Union{Range{Int64},Colon,Array{Int64,1},Int64}}},LD}]
````

**Comment by GordStephen** [comment]
In this context `DenseArray` seems to be the only `AbstractArray` subtype of relevance... I'll do some speed tests for the various levels of specificity though.

**Comment by milktrader** [comment]
Yep, agreed, and looking forward to the benchmarks

**Comment by GordStephen** [comment]
Seems like it's a wash, performance-wise:

`Array{T,N}` (`master`):
```julia
julia> using MarketData
julia> @elapsed AAPL["Close"] .+ BA["Close"]
0.043117468
```

`Union{Array{T,N},BitArray{N}}`:
```julia
julia> using MarketData
julia> @elapsed AAPL["Close"] .+ BA["Close"]
0.04327045
```

`DenseArray{T,N}` (this PR):
```julia
julia> using MarketData
julia> @elapsed AAPL["Close"] .+ BA["Close"]
0.04161412
```

`AbstractArray{T,N}`:
```julia
julia> using MarketData
julia> @elapsed AAPL["Close"] .+ BA["Close"]
0.04547258
```

Personally I'd lean towards `DenseArray` as a balance between generality and meaningful type restrictions.

**Comment by milktrader** [comment]
Ok, thanks. In my mind it's `DenseArray` first, a work-around second and `Union{Array, BitArray}` last.

**Comment by milktrader** [comment]
Just a copy-paste of the docs for reference
>DenseArray is an abstract subtype of AbstractArray intended to include all arrays that are laid out at regular offsets in memory, and which can therefore be passed to external C and Fortran functions expecting this memory layout. Subtypes should provide a method stride(A,k) that returns the “stride” of dimension k: increasing the index of dimension k by 1 should increase the index i of getindex(A,i) by stride(A,k). If a pointer conversion method convert(Ptr{T}, A) is provided, the memory layout should correspond in the same way to these strides.

The Array type is a specific instance of DenseArray where elements are stored in column-major order (see additional notes in Performance Tips). Vector and Matrix are aliases for the 1-d and 2-d cases. Specific operations such as scalar indexing, assignment, and a few other basic storage-specific operations are all that have to be implemented for :obj:`Array, so that the rest of the array library can be implemented in a generic manner.

**Comment by GordStephen** [comment]
https://github.com/GordStephen/TimeSeries.jl/commit/3de4ebdca746637b1649d6aee5531a84ad9d020d  just adds a few new operators and relevants tests / docs - nothing too major. I'll probably push the refactoring elements of https://github.com/JuliaStats/TimeSeries.jl/pull/195 as another commit tomorrow.

**Comment by milktrader** [comment]
Running this PR locally I'm not seeing any problems. My only concern is that there is some yet unknown effect. On the plus side, 

* performance is unaffected
* new operators are intoduced
* all tests are still passing

I need to grok the difference between `BitArray` and `Array{Bool, N}`.

**Comment by milktrader** [comment]
ping @quinnj long story short is the replacement of the `values` element from `Array` to `DenseArray`, which provides support for `BitArray`

**Comment by milktrader** [comment]
I've posted on google groups for a little feedback, but I think this implementation is probably the one to go with. https://groups.google.com/forum/#!topic/julia-dev/GwNwuwZflNI

**Comment by milktrader** [comment]
@GordStephen there is some good feedback on the google groups post I did (link above). Apparently there is some question if `BitArray` is faster or slower than `Array{Bool,N}`. There is also some consensus building around using `AbstractArray` in any case, since using `DenseArray` has an expressed goal of being able to pass the object to BLAS, and that's not the case in `TimeArray`.

Maybe the least impact way to get the bitwise operators into the code is to have them return `Array{Bool.N}` for now and then we can discuss the merits of reworking the values component into an `AbstractArray`.

What do you think?

**Comment by GordStephen** [comment]
I'm ok just to hold off on merging until the AbstractArray question has been settled - no point in implementing a workaround just to potentially change it again later (in the meantime, if anyone desperately needs bitwise operations, they can always pull in this fork themselves).

I don't see any mention of potential side-effects of switching to AbstractArray in that thread - as I understand it, generalizing would just allow TimeArray to wrap more types, but doesn't remove or change any existing functionality (but famous last words, maybe...)?

**Comment by GordStephen** [comment]
Any new thoughts on this? Happy to address the merge conflicts if/when we choose to go ahead.

**Comment by milktrader** [comment]
I say we go for this with the first tag that supports Julia 0.4, coming soon. Hopefully get to this today.

What did we decide was our best course here? `AbstratctArray` or `DenseArray`? I recall `AbstractArray` was the preferred choice.

**Comment by GordStephen** [comment]
Yeah, I think the consensus settled on AbstractArray - the latest commit in this PR implemented that.

**Comment by milktrader** [comment]
Ok, great. I'll tag up 0.5.11 (last version supporting Julia 03) and then 0.6.0 (first version supporting Julia 0.4 only) and then you can take it from there and tag 0.6.1 with the AbstractArray implementation. 

Remember to add a line to NEWS.md about the important improvement.

**Comment by GordStephen** [comment]
Superseded by https://github.com/JuliaStats/TimeSeries.jl/pull/205

**Pull request closed without merging**
