### PR TITLE
timearray: refine pretty printing

### PR DESCRIPTION
**Pull request by iblis17**
- DataFrames-like printing

- make printing fit for `displaysize`

- remove `SHOWINT`

- implement paging.
  e.g.: `using MarketData; AAPL`

Sample output:

```julia
julia> ohlc
500x4 TimeSeries.TimeArray{Float64,2,Date,Array{Float64,2}} 2000-01-03 to 2001-12-31
│            │ TestSoLong │ High   │ Low    │ Close  │
├────────────┼────────────┼────────┼────────┼────────┤
│ 2000-01-03 │ 104.88     │ 112.5  │ 101.69 │ 111.94 │
│ 2000-01-04 │ 108.25     │ 110.62 │ 101.19 │ 102.5  │
│ 2000-01-05 │ 103.75     │ 110.56 │ 103.0  │ 104.0  │
│ 2000-01-06 │ 106.12     │ 107.0  │ 95.0   │ 95.0   │
│ 2000-01-07 │ 96.5       │ 101.0  │ 95.5   │ 99.5   │
│ 2000-01-10 │ 102.0      │ 102.25 │ 94.75  │ 97.75  │
│ 2000-01-11 │ 95.94      │ 99.38  │ 90.5   │ 92.75  │
│ 2000-01-12 │ 95.0       │ 95.5   │ 86.5   │ 87.19  │
│ 2000-01-13 │ 94.48      │ 98.75  │ 92.5   │ 96.75  │
│ 2000-01-14 │ 100.0      │ 102.25 │ 99.38  │ 100.44 │
│ 2000-01-18 │ 101.0      │ 106.0  │ 100.44 │ 103.94 │
│ 2000-01-19 │ 105.62     │ 108.75 │ 103.38 │ 106.56 │
   ⋮
│ 2001-12-14 │ 20.73      │ 20.83  │ 20.09  │ 20.39  │
│ 2001-12-17 │ 20.4       │ 21.0   │ 20.19  │ 20.62  │
│ 2001-12-18 │ 20.89      │ 21.33  │ 20.22  │ 21.01  │
│ 2001-12-19 │ 20.58      │ 21.68  │ 20.47  │ 21.62  │
│ 2001-12-20 │ 21.4       │ 21.47  │ 20.62  │ 20.67  │
│ 2001-12-21 │ 21.01      │ 21.54  │ 20.8   │ 21.0   │
│ 2001-12-24 │ 20.9       │ 21.45  │ 20.9   │ 21.36  │
│ 2001-12-26 │ 21.35      │ 22.3   │ 21.14  │ 21.49  │
│ 2001-12-27 │ 21.58      │ 22.25  │ 21.58  │ 22.07  │
│ 2001-12-28 │ 21.97      │ 23.0   │ 21.96  │ 22.43  │
│ 2001-12-31 │ 22.51      │ 22.66  │ 21.83  │ 21.9   │

julia>
```

### CODE REVIEW

**Comment by iblis17** [comment]
this PR should fix #330

**Comment by ararslan** [comment]
That output looks really nice. Good work! It might be worthwhile to add a test that ensures that `sprint(show, ta)` (for `ta` a `TimeArray`) matches some expected output string.

**Comment by iblis17** [comment]
simple test cases added.

**Comment by iblis17** [comment]
good to go?

**Comment by ararslan** [comment]
I think there should be a test along the lines of
```julia
@test sprint(show, something) == """
│            │ TestSoLong │ High   │ Low    │ Close  │
├────────────┼────────────┼────────┼────────┼────────┤
│ 2000-01-03 │ 104.88     │ 112.5  │ 101.69 │ 111.94 │
│ 2000-01-04 │ 108.25     │ 110.62 │ 101.19 │ 102.5  │
│ 2000-01-05 │ 103.75     │ 110.56 │ 103.0  │ 104.0  │
│ 2000-01-06 │ 106.12     │ 107.0  │ 95.0   │ 95.0   │
│ 2000-01-07 │ 96.5       │ 101.0  │ 95.5   │ 99.5   │
│ 2000-01-10 │ 102.0      │ 102.25 │ 94.75  │ 97.75  │
│ 2000-01-11 │ 95.94      │ 99.38  │ 90.5   │ 92.75  │
│ 2000-01-12 │ 95.0       │ 95.5   │ 86.5   │ 87.19  │
│ 2000-01-13 │ 94.48      │ 98.75  │ 92.5   │ 96.75  │
│ 2000-01-14 │ 100.0      │ 102.25 │ 99.38  │ 100.44 │
│ 2000-01-18 │ 101.0      │ 106.0  │ 100.44 │ 103.94 │
│ 2000-01-19 │ 105.62     │ 108.75 │ 103.38 │ 106.56 │
"""
```
This ensures that the column alignment, rounding, values, and all of that is as expected. It's a more exact test than using `contains`.

**Comment by iblis17** [comment]
👌 done

**Pull request merged**
