### PR TITLE
Rtd

### PR DESCRIPTION
**Pull request by milktrader**

### CODE REVIEW

**Comment by MrTomWhite** [comment]
Since everything in `/_build` Is generated from the make script, does it need to be committed to the repository?

**Comment by milktrader** [comment]
I'm not sure and the answer is probably no. How would you handle this? Add it to .gitignore or just remove it before committing?

**Comment by milktrader** [comment]
Hmm, I see that readthedocs can't build it the way it's presently laid out. It clearly doesn't care what's in the `_build` directory.

**Comment by MrTomWhite** [comment]
I would probably do both so no one else makes the same commit again. :)

**Comment by milktrader** [comment]
https://github.com/JuliaStats/TimeSeries.jl/issues/176

**Comment by milktrader** [comment]
thanks @MrTomWhite

**Pull request merged**
