### PR TITLE
 Support delimiter, header and format when writing time series

### PR DESCRIPTION
**Pull request by petershintech**
To make writetimearray() symmetric with readtimearray().

### CODE REVIEW

**Comment by petershintech** [comment]
Knock, knock. Anybody who can review these commits?

**Comment by iblis17** [comment]
ha, okay

**Comment by petershintech** [comment]
Glad to have attention to my PR.  @iblis17 I think this is a nice extension. Please let me know if you have any suggestions.

**Comment by iblis17** [comment]
I will find free time to test this patch in following few days.

**Comment by iblis17** [comment]
Thanks for this great contributions! :+1:

**Pull request merged**
