### PR TITLE
Replace find -> findall and fix issue 432

### LINKED ISSUE #432: Plotting TimeArray with seriestype == :candlestick causes exception "UndefVarError: find not defined"
When plotting a `TimeArray` using `seriestype = :candlestick`, I get the following exception:

```
UndefVarError: find not defined
```

caused at [plotrecipes.jl:27](https://github.com/JuliaStats/TimeSeries.jl/blob/v0.16.0/src/plotrecipes.jl#L27). I'm using v0.16.0 of TimeSeries.jl and Julia 1.12. Indeed, the function `find` is not defined. The code in `plotrecipes.jl` seems not to have changed between v0.16.0 and `master`.

### PR DESCRIPTION
**Pull request by Sh4pe**
The function find is not defined and caused an UndefVarError
when this line was executed.

Fixes #432

### CODE REVIEW

**Comment by iblis17** [comment]
Hi @Sh4pe could you test the updated patches?

**Comment by Sh4pe** [comment]
It still does not work and fails inside `extract_ohlc`. I've added a test that invokes the `Candlestick` constructor and [it fails](https://travis-ci.org/JuliaStats/TimeSeries.jl/jobs/598303378#L375) with the error message 

```
ArgumentError: invalid index: nothing of type Nothing
```
(The [Julia 1.0 build job](https://travis-ci.org/JuliaStats/TimeSeries.jl/jobs/598303379#L284) failed because it could not connect to GitHub. Maybe it needs to be rekicked).

**Comment by iblis17** [comment]
ah, I fixed the error message.
A Candlestick requires theses four columns as inputs: `open`, `high`, `low`, `close`.
A worked example:
```julia
using MarketData
TimeSeries.Candlestick(ohlcv)
```

**Comment by Sh4pe** [comment]
Ok, got it. Didn't know that these columns have to be present. Maybe a short comment in [plotting.md](https://github.com/JuliaStats/TimeSeries.jl/blob/master/docs/src/plotting.md) should be added saying that these columns are required for a candlestick plot. What do you think?

**Comment by iblis17** [comment]
Thanks for your contribution.

I'm going to make a new release.

**Pull request merged**
